### ISSUE TITLE
sv_ag_start commands do not work

### ISSUE THREAD

**Issue by sabianroberts** [fireblizzard/agmod#1]
With gamemodes such as Arcade, which spawns you with all weapons, the `sv_ag_start` commands do not work. The player still spawns with a 9mm Handgun and a crowbar. No suit power nor longjump either.

**Comment by sabianroberts** [comment]
ef481a68fc70e0972a529d7f8edba0a905a76e9d fixed this issue.

Thanks @fireblizzard!

**Comment by fireblizzard** [comment]
Thanks to you for reporting. It would have taken me some time to realize about this regression :)
