### ISSUE TITLE
Issue with Linux build

### ISSUE THREAD

**Issue by ghost** [fireblizzard/agmod#14]
I have tried both Ubuntu focal and Debian bullseye, with the same results. gcc:i386 and gcc:amd64 also result in the same problem. The build completes fine, but as soon as I try to run it in a server, it completely falls apart due to a linking error. I have attached the  `ldd -v -r` output.

[ldd.txt](https://github.com/fireblizzard/agmod/files/8674503/ldd.txt)

**Comment by fireblizzard** [comment]
Avoid using the libstdc6++ that comes with Steam. Try symlinking the one you have in `/usr/lib/x86_64-linux-gnu/libstdc++.so.6` or similar into your HLDS directory. Hope that helps and sorry for the delay, I don't have much time for this

**Comment by BryanHaley** [comment]
Noting: in order to do this fix I also had to symlink `/usr/lib/x86_64-linux-gnu/libgcc_s.so.1`, because `libstdc++.so.6` tries to load it, and if it finds the one in the Half-Life dir it fails because it's too old.
