### ISSUE TITLE
Broken Hitboxes on Linux Server

### ISSUE THREAD

**Issue by JONERAGILT** [fireblizzard/agmod#18]
The hitboxes for weapons are way to big and tried a fresh install, which didn't work. server is still broken. I'm not sure as to how to fix it.

**Comment by fireblizzard** [comment]
I'm not sure how to help you either. I would need some info:
- Is it HLDS or ReHLDS? what version?
- Do you have addons installed? if so, which ones and which versions, and the same with plugins
- Output of `cvarlist` without sensitive info like passwords
- Video footage showing how big the hitboxes are

**Comment by JONERAGILT** [comment]
oh sorry, i forgot about this; it's fixed now; we did some troubleshooting and rehlds wasn't up to date. so it's all good now.
